FROM ubuntu
MAINTAINER Marcel Grossmann <whatever4711@gmail.com>

RUN apt-get update
RUN apt-get install -y git build-essential binutils
ENV ARMBIAN=/armbian
RUN mkdir $ARMBIAN && \
    cd $ARMBIAN && \
    git clone https://github.com/igorpecovnik/lib --depth 1 && \
    cp lib/compile.sh .

WORKDIR $ARMBIAN
ENTRYPOINT ["./compile.sh"]
